[package]
name = "bolt-ctl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bolt-ctl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteordered = "0.6.0"

[profile.release]
lto = true
panic = "abort"
